### ISSUE TITLE
Improvement for vertical installation

### ISSUE THREAD

**Issue by RaphaelDives** [RealNagus/CustomizableCableDuct#1]
Hey there,
I created a vertical cable duct but the cover slides down, so I modified the OpenScad document for a small lid on the cover.
Maybe this could be useful for some others as well?
I could post the changes, or create a fork for it by interest?
![cableduct](https://github.com/user-attachments/assets/5da3dd79-6929-4b74-a086-9ac07bb3b129)

Cheers,
Raphael

**Comment by RealNagus** [comment]
Hey. That's a great idea, looks pretty good! I'll happily incorporate the feature. Would you create a PR from your fork?
